---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

######## Server JSON ############################
appender.rolling.type: RollingFile
appender.rolling.name: rolling
appender.rolling.fileName: ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_server.json
appender.rolling.layout.type: ESJsonLayout
appender.rolling.layout.type_name: server
appender.rolling.filePattern: ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}-%d{yyyy-MM-dd}-%i.json.gz
appender.rolling.policies.type: Policies
appender.rolling.policies.time.type: TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval: 1
appender.rolling.policies.time.modulate: true
appender.rolling.policies.size.type: SizeBasedTriggeringPolicy
appender.rolling.policies.size.size: 256MB
appender.rolling.strategy.type: DefaultRolloverStrategy
appender.rolling.strategy.fileIndex: nomax
appender.rolling.strategy.action.type: Delete
appender.rolling.strategy.action.basepath: ${sys:es.logs.base_path}
appender.rolling.strategy.action.condition.type: IfFileName
appender.rolling.strategy.action.condition.glob: ${sys:es.logs.cluster_name}-*
appender.rolling.strategy.action.condition.nested_condition.type: IfAccumulatedFileSize
appender.rolling.strategy.action.condition.nested_condition.exceeds: 1GB
################################################
